# TCL File Generated by Component Editor 18.1
# Sat May 27 22:10:38 BST 2023
# DO NOT MODIFY


# 
# avalon_st_to_mm_buffer "Avalon Memory-Mapped Stream Sink" v1.0
# Shuyuan Liu 2023.05.27.22:10:38
# A memory-mapped buffer that stores incoming data from a streaming interface
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_st_to_mm_buffer
# 
set_module_property DESCRIPTION "A memory-mapped buffer that stores incoming data from a streaming interface"
set_module_property NAME avalon_st_to_mm_buffer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Shuyuan Liu"
set_module_property DISPLAY_NAME "Avalon Memory-Mapped Stream Sink"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_st_to_mm_buffer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_st_to_mm_buffer.sv SYSTEM_VERILOG PATH ip/avalon_st_to_mm_buffer/avalon_st_to_mm_buffer.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter bufferSize INTEGER 307200
set_parameter_property bufferSize DEFAULT_VALUE 307200
set_parameter_property bufferSize DISPLAY_NAME bufferSize
set_parameter_property bufferSize TYPE INTEGER
set_parameter_property bufferSize UNITS None
set_parameter_property bufferSize ALLOWED_RANGES -2147483648:2147483647
set_parameter_property bufferSize HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point stream_sink
# 
add_interface stream_sink avalon_streaming end
set_interface_property stream_sink associatedClock stream_clock
set_interface_property stream_sink associatedReset reset
set_interface_property stream_sink dataBitsPerSymbol 8
set_interface_property stream_sink errorDescriptor ""
set_interface_property stream_sink firstSymbolInHighOrderBits true
set_interface_property stream_sink maxChannel 0
set_interface_property stream_sink readyLatency 1
set_interface_property stream_sink ENABLED true
set_interface_property stream_sink EXPORT_OF ""
set_interface_property stream_sink PORT_NAME_MAP ""
set_interface_property stream_sink CMSIS_SVD_VARIABLES ""
set_interface_property stream_sink SVD_ADDRESS_GROUP ""

add_interface_port stream_sink sink_data data Input 24
add_interface_port stream_sink sink_valid valid Input 1
add_interface_port stream_sink sink_ready ready Output 1
add_interface_port stream_sink sink_endofpacket endofpacket Input 1
add_interface_port stream_sink sink_startofpacket startofpacket Input 1


# 
# connection point mm_clock
# 
add_interface mm_clock clock end
set_interface_property mm_clock clockRate 0
set_interface_property mm_clock ENABLED true
set_interface_property mm_clock EXPORT_OF ""
set_interface_property mm_clock PORT_NAME_MAP ""
set_interface_property mm_clock CMSIS_SVD_VARIABLES ""
set_interface_property mm_clock SVD_ADDRESS_GROUP ""

add_interface_port mm_clock mm_clock clk Input 1


# 
# connection point stream_clock
# 
add_interface stream_clock clock end
set_interface_property stream_clock clockRate 0
set_interface_property stream_clock ENABLED true
set_interface_property stream_clock EXPORT_OF ""
set_interface_property stream_clock PORT_NAME_MAP ""
set_interface_property stream_clock CMSIS_SVD_VARIABLES ""
set_interface_property stream_clock SVD_ADDRESS_GROUP ""

add_interface_port stream_clock sink_clock clk Input 1


# 
# connection point mm_interface
# 
add_interface mm_interface avalon end
set_interface_property mm_interface addressUnits WORDS
set_interface_property mm_interface associatedClock mm_clock
set_interface_property mm_interface associatedReset reset
set_interface_property mm_interface bitsPerSymbol 8
set_interface_property mm_interface burstOnBurstBoundariesOnly false
set_interface_property mm_interface burstcountUnits WORDS
set_interface_property mm_interface explicitAddressSpan 0
set_interface_property mm_interface holdTime 0
set_interface_property mm_interface linewrapBursts false
set_interface_property mm_interface maximumPendingReadTransactions 0
set_interface_property mm_interface maximumPendingWriteTransactions 0
set_interface_property mm_interface readLatency 0
set_interface_property mm_interface readWaitTime 1
set_interface_property mm_interface setupTime 0
set_interface_property mm_interface timingUnits Cycles
set_interface_property mm_interface writeWaitTime 0
set_interface_property mm_interface ENABLED true
set_interface_property mm_interface EXPORT_OF ""
set_interface_property mm_interface PORT_NAME_MAP ""
set_interface_property mm_interface CMSIS_SVD_VARIABLES ""
set_interface_property mm_interface SVD_ADDRESS_GROUP ""

add_interface_port mm_interface mm_chipselect chipselect Input 1
add_interface_port mm_interface mm_address address Input 1
add_interface_port mm_interface mm_read read Input 1
add_interface_port mm_interface mm_readdata readdata Output 32
add_interface_port mm_interface mm_write write Input 1
add_interface_port mm_interface mm_writedata writedata Input 32
set_interface_assignment mm_interface embeddedsw.configuration.isFlash 0
set_interface_assignment mm_interface embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_interface embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_interface embeddedsw.configuration.isPrintableDevice 0

